FROM node:14.16-alpine

ARG APP_LNMARKETS_PORT
WORKDIR /usr/src

COPY package.json yarn.lock ./
COPY apps/front/package.json apps/front/package.json
COPY apps/front/src/plugins/client.js apps/front/src/plugins/client.js
RUN yarn install --frozen-lockfile

WORKDIR /usr/src/apps/front

EXPOSE 3000

CMD sed -i "s/'VUE_APP_LNMARKETS_PORT'/${APP_LNMARKETS_PORT}/g" src/plugins/client.js && yarn workspace front dev 
