FROM node:18.15.0-alpine3.16

WORKDIR /usr/src

RUN npm install -g pnpm@8

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/front/package.json apps/front/package.json

RUN pnpm config set store-dir .pnpm-store
RUN pnpm install --frozen-lockfile --ignore-scripts


CMD ["sh", "-c", "pnpm run -C apps/front dev"] 
