FROM node:14.16-alpine

WORKDIR /usr/src

COPY package.json yarn.lock ./
COPY apps/front/package.json apps/front/package.json
COPY apps/front/src/plugins/client.js apps/front/src/plugins/client.js
RUN yarn install --frozen-lockfile

WORKDIR /usr/src/apps/front

CMD ["yarn", "workspace", "front", "dev"] 
