name: lnmarkets-umbrel

x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '10'
    tag: '{{.Name}}'
networks:
  lnmarkets_backend:
    external: true
  lnmarkets_reverse-proxy:
    external: true

volumes:
  lnmarkets_lnd-user:
    external: true

services:
  api:
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile.dev
    ports:
      - 8001:4242
    environment:
      - NODE_ENV=development
      - LND_IP=lnd-user
      - LNMARKETS_API_HOSTNAME=api.afa.lnmarkets.dev
      - BITCOIN_NETWORK=regtest
      - APP_PASSWORD=lnmarkets
    volumes:
      - ../apps/api/src:/usr/src/apps/api/src
      - lnmarkets_lnd-user:/lnd:ro
    networks:
      - lnmarkets_backend
      - lnmarkets_reverse-proxy
    logging: *default-logging

  front:
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./apps/front/docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ../apps/front/src:/usr/src/apps/front/src
      - ../apps/front/public:/usr/src/apps/front/public
      - ../apps/front/postcss.config.js:/usr/src/apps/front/postcss.config.js
      - ../apps/front/tailwind.config.js:/usr/src/apps/front/tailwind.config.js
      - ../apps/front/vite.config.js:/usr/src/apps/front/vite.config.js
      - ../apps/front/index.html:/usr/src/apps/front/index.html
    environment:
      - NODE_ENV=development
    logging: *default-logging

  # This service is used to test the production container
  # We run as root to avoid permissions issues in the lnd volume
  app:
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./Dockerfile
    user: root
    ports:
      - 4242:4242
    environment:
      - LND_IP=lnmarkets_lnd_user
      - LNMARKETS_API_HOSTNAME=api.kibotrel.lnmarkets.dev
      - BITCOIN_NETWORK=regtest
      - APP_PASSWORD=lnmarkets
    volumes:
      - lnmarkets_lnd-user:/lnd:ro
    networks:
      - lnmarkets_backend
      - lnmarkets_reverse-proxy
    logging: *default-logging
