FROM node:14.16-alpine

WORKDIR /usr/src

COPY package.json yarn.lock ./
COPY apps/api/package.json apps/api/package.json

RUN yarn install --frozen-lockfile

CMD [ "yarn", "workspace", "api", "dev" ]
