name: build-and-push-latest

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v3
        with:
          username: vafanassieff
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/ln-markets/umbrel
            lnmarkets/umbrel
          tags: |
            type=ref,event=branch
            type=sha

      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
